# Generated by Django 2.2 on 2020-12-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_1', models.CharField(max_length=100)),
                ('tc_2', models.CharField(max_length=100)),
                ('tc_3', models.CharField(max_length=100)),
                ('tc_4', models.CharField(max_length=100)),
                ('molecule', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('corporation', models.CharField(max_length=100)),
                ('manuf_type', models.CharField(max_length=100)),
                ('formulation', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('molecule_tc', models.CharField(max_length=100)),
                ('product_corp', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('date_time', models.DateField()),
            ],
            options={
                'db_table': 'test_data',
            },
        ),
    ]
