# Generated by Django 2.2 on 2020-12-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chpa_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdata',
            name='molecule_tc',
        ),
        migrations.RemoveField(
            model_name='testdata',
            name='product_corp',
        ),
    ]
